In [1]:
print("OK")

OK

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Visadataset.csv")
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [3]:
df.shape

(25480, 12)

In [4]:
df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [17]:
data = df.to_dict(orient='records')
data[0]

{'_id': ObjectId('65ecad12116c88192e9c277c'),
 'case_id': 'EZYV01',
 'continent': 'Asia',
 'education_of_employee': 'High School',
 'has_job_experience': 'N',
 'requires_job_training': 'N',
 'no_of_employees': 14513,
 'yr_of_estab': 2007,
 'region_of_employment': 'West',
 'prevailing_wage': 592.2029,
 'unit_of_wage': 'Hour',
 'full_time_position': 'Y',
 'case_status': 'Denied'}

In [18]:
DB_NAME = "VISA"
COLLECTION_NAME = "us_visa_prediction"
CONNECTION_URL = "MONGODB_URL"

In [8]:
import pymongo

In [10]:
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]
rec = collection.insert_many(data)

In [11]:
records = collection.find()
records

In [12]:
for i, j in enumerate(records):
    print(f"{i}: {j}")

0: {'_id': ObjectId('65ecad12116c88192e9c277c'), 'case_id': 'EZYV01', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 14513, 'yr_of_estab': 2007, 'region_of_employment': 'West', 'prevailing_wage': 592.2029, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Denied'}
1: {'_id': ObjectId('65ecad12116c88192e9c277d'), 'case_id': 'EZYV02', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2412, 'yr_of_estab': 2002, 'region_of_employment': 'Northeast', 'prevailing_wage': 83425.65, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
2: {'_id': ObjectId('65ecad12116c88192e9c277e'), 'case_id': 'EZYV03', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'Y', 'no_of_employees': 44444, 'yr_of_estab': 2008, 'region_of_employment': 'West', 'prevailing_wage': 122996.86, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
3: {'_id': ObjectId('65ecad12116c88192e9c277f'), 'case_id': 'EZYV04', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 98, 'yr_of_estab': 1897, 'region_of_employment': 'West', 'prevailing_wage': 83434.03, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
4: {'_id': ObjectId('65ecad12116c88192e9c2780'), 'case_id': 'EZYV05', 'continent': 'Africa', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1082, 'yr_of_estab': 2005, 'region_of_employment': 'South', 'prevailing_wage': 149907.39, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
5: {'_id': ObjectId('65ecad12116c88192e9c2781'), 'case_id': 'EZYV06', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2339, 'yr_of_estab': 2012, 'region_of_employment': 'South', 'prevailing_wage': 78252.14, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
6: {'_id': ObjectId('65ecad12116c88192e9c2782'), 'case_id': 'EZYV07', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 4985, 'yr_of_estab': 1994, 'region_of_employment': 'South', 'prevailing_wage': 53635.39, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
7: {'_id': ObjectId('65ecad12116c88192e9c2783'), 'case_id': 'EZYV08', 'continent': 'North America', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 3035, 'yr_of_estab': 1924, 'region_of_employment': 'West', 'prevailing_wage': 418.2298, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Denied'}
8: {'_id': ObjectId('65ecad12116c88192e9c2784'), 'case_id': 'EZYV09', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 4810, 'yr_of_estab': 2012, 'region_of_employment': 'Midwest', 'prevailing_wage': 74362.19, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
9: {'_id': ObjectId('65ecad12116c88192e9c2785'), 'case_id': 'EZYV10', 'continent': 'Europe', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2251, 'yr_of_estab': 1995, 'region_of_employment': 'South', 'prevailing_wage': 67514.76, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
10: {'_id': ObjectId('65ecad12116c88192e9c2786'), 'case_id': 'EZYV11', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2465, 'yr_of_estab': 2004, 'region_of_employment': 'Midwest', 'prevailing_wage': 83588.56, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
11: {'_id': ObjectId('65ecad12116c88192e9c2787'), 'case_id': 'EZYV12', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 4069, 'yr_of_estab': 2005, 'region_of_employment': 'Northeast', 'prevailing_wage': 70813.09, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
12: {'_id': ObjectId('65ecad12116c88192e9c2788'), 'case_id': 'EZYV13', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 123876, 'yr_of_estab': 1963, 'region_of_employment': 'Northeast', 'prevailing_wage': 28663.05, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
13: {'_id': ObjectId('65ecad12116c88192e9c2789'), 'case_id': 'EZYV14', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1652, 'yr_of_estab': 2007, 'region_of_employment': 'Midwest', 'prevailing_wage': 107196.03, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
14: {'_id': ObjectId('65ecad12116c88192e9c278a'), 'case_id': 'EZYV15', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 15756, 'yr_of_estab': 2006, 'region_of_employment': 'South', 'prevailing_wage': 220081.73, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
15: {'_id': ObjectId('65ecad12116c88192e9c278b'), 'case_id': 'EZYV16', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 4897, 'yr_of_estab': 1987, 'region_of_employment': 'West', 'prevailing_wage': 74108.02, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
16: {'_id': ObjectId('65ecad12116c88192e9c278c'), 'case_id': 'EZYV17', 'continent': 'Europe', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 76638, 'yr_of_estab': 1991, 'region_of_employment': 'Midwest', 'prevailing_wage': 3706.79, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
17: {'_id': ObjectId('65ecad12116c88192e9c278d'), 'case_id': 'EZYV18', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2747, 'yr_of_estab': 2001, 'region_of_employment': 'West', 'prevailing_wage': 16132.61, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
18: {'_id': ObjectId('65ecad12116c88192e9c278e'), 'case_id': 'EZYV19', 'continent': 'Africa', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 4743, 'yr_of_estab': 2004, 'region_of_employment': 'Midwest', 'prevailing_wage': 150441.13, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
19: {'_id': ObjectId('65ecad12116c88192e9c278f'), 'case_id': 'EZYV20', 'continent': 'Asia', 'education_of_employee': 'Doctorate', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 843, 'yr_of_estab': 1972, 'region_of_employment': 'Midwest', 'prevailing_wage': 79948.12, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20: {'_id': ObjectId('65ecad12116c88192e9c2790'), 'case_id': 'EZYV21', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 880, 'yr_of_estab': 2008, 'region_of_employment': 'West', 'prevailing_wage': 71128.98, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
21: {'_id': ObjectId('65ecad12116c88192e9c2791'), 'case_id': 'EZYV22', 'continent': 'North America', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1706, 'yr_of_estab': 2013, 'region_of_employment': 'Midwest', 'prevailing_wage': 137694.98, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
22: {'_id': ObjectId('65ecad12116c88192e9c2792'), 'case_id': 'EZYV23', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2878, 'yr_of_estab': 1968, 'region_of_employment': 'West', 'prevailing_wage': 45642.39, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
23: {'_id': ObjectId('65ecad12116c88192e9c2793'), 'case_id': 'EZYV24', 'continent': 'North America', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1517, 'yr_of_estab': 1884, 'region_of_employment': 'Midwest', 'prevailing_wage': 90108.38, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
24: {'_id': ObjectId('65ecad12116c88192e9c2794'), 'case_id': 'EZYV25', 'continent': 'Europe', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 241, 'yr_of_estab': 1981, 'region_of_employment': 'Midwest', 'prevailing_wage': 71286.04, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
25: {'_id': ObjectId('65ecad12116c88192e9c2795'), 'case_id': 'EZYV26', 'continent': 'North America', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1100, 'yr_of_estab': 1997, 'region_of_employment': 'Midwest', 'prevailing_wage': 99489.65, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
26: {'_id': ObjectId('65ecad12116c88192e9c2796'), 'case_id': 'EZYV27', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 756, 'yr_of_estab': 1995, 'region_of_employment': 'South', 'prevailing_wage': 86332.95, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
27: {'_id': ObjectId('65ecad12116c88192e9c2797'), 'case_id': 'EZYV28', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 2889, 'yr_of_estab': 2005, 'region_of_employment': 'South', 'prevailing_wage': 103029.33, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
28: {'_id': ObjectId('65ecad12116c88192e9c2798'), 'case_id': 'EZYV29', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 18, 'yr_of_estab': 2004, 'region_of_employment': 'Northeast', 'prevailing_wage': 40925.86, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
29: {'_id': ObjectId('65ecad12116c88192e9c2799'), 'case_id': 'EZYV30', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 758, 'yr_of_estab': 2009, 'region_of_employment': 'Northeast', 'prevailing_wage': 189190.48, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
30: {'_id': ObjectId('65ecad12116c88192e9c279a'), 'case_id': 'EZYV31', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1408, 'yr_of_estab': 1998, 'region_of_employment': 'Midwest', 'prevailing_wage': 79594.12, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
31: {'_id': ObjectId('65ecad12116c88192e9c279b'), 'case_id': 'EZYV32', 'continent': 'Asia', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 995, 'yr_of_estab': 1880, 'region_of_employment': 'South', 'prevailing_wage': 135866.13, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
32: {'_id': ObjectId('65ecad12116c88192e9c279c'), 'case_id': 'EZYV33', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2415, 'yr_of_estab': 1963, 'region_of_employment': 'Midwest', 'prevailing_wage': 72077.57, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
33: {'_id': ObjectId('65ecad12116c88192e9c279d'), 'case_id': 'EZYV34', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2395, 'yr_of_estab': 2000, 'region_of_employment': 'South', 'prevailing_wage': 81921.18, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
34: {'_id': ObjectId('65ecad12116c88192e9c279e'), 'case_id': 'EZYV35', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1809, 'yr_of_estab': 2010, 'region_of_employment': 'South', 'prevailing_wage': 225569.73, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
35: {'_id': ObjectId('65ecad12116c88192e9c279f'), 'case_id': 'EZYV36', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 5512, 'yr_of_estab': 2001, 'region_of_employment': 'Northeast', 'prevailing_wage': 92421.92, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
36: {'_id': ObjectId('65ecad12116c88192e9c27a0'), 'case_id': 'EZYV37', 'continent': 'Europe', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2520, 'yr_of_estab': 1981, 'region_of_employment': 'West', 'prevailing_wage': 2490.12, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
37: {'_id': ObjectId('65ecad12116c88192e9c27a1'), 'case_id': 'EZYV38', 'continent': 'Europe', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 44, 'yr_of_estab': 1965, 'region_of_employment': 'South', 'prevailing_wage': 110817.26, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
38: {'_id': ObjectId('65ecad12116c88192e9c27a2'), 'case_id': 'EZYV39', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 2206, 'yr_of_estab': 1909, 'region_of_employment': 'Northeast', 'prevailing_wage': 50960.01, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
39: {'_id': ObjectId('65ecad12116c88192e9c27a3'), 'case_id': 'EZYV40', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 3729, 'yr_of_estab': 2007, 'region_of_employment': 'Midwest', 'prevailing_wage': 125336.9, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
40: {'_id': ObjectId('65ecad12116c88192e9c27a4'), 'case_id': 'EZYV41', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 3723, 'yr_of_estab': 2011, 'region_of_employment': 'West', 'prevailing_wage': 39633.32, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
41: {'_id': ObjectId('65ecad12116c88192e9c27a5'), 'case_id': 'EZYV42', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1209, 'yr_of_estab': 1989, 'region_of_employment': 'Northeast', 'prevailing_wage': 156326.33, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
42: {'_id': ObjectId('65ecad12116c88192e9c27a6'), 'case_id': 'EZYV43', 'continent': 'Europe', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 19770, 'yr_of_estab': 2005, 'region_of_employment': 'West', 'prevailing_wage': 43630.58, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
43: {'_id': ObjectId('65ecad12116c88192e9c27a7'), 'case_id': 'EZYV44', 'continent': 'North America', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2582, 'yr_of_estab': 1989, 'region_of_employment': 'South', 'prevailing_wage': 54614.42, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
44: {'_id': ObjectId('65ecad12116c88192e9c27a8'), 'case_id': 'EZYV45', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 5407, 'yr_of_estab': 1998, 'region_of_employment': 'West', 'prevailing_wage': 28989.87, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
45: {'_id': ObjectId('65ecad12116c88192e9c27a9'), 'case_id': 'EZYV46', 'continent': 'Europe', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'Y', 'no_of_employees': 2092, 'yr_of_estab': 1998, 'region_of_employment': 'South', 'prevailing_wage': 22924.91, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
46: {'_id': ObjectId('65ecad12116c88192e9c27aa'), 'case_id': 'EZYV47', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2623, 'yr_of_estab': 2008, 'region_of_employment': 'South', 'prevailing_wage': 61567.75, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
47: {'_id': ObjectId('65ecad12116c88192e9c27ab'), 'case_id': 'EZYV48', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 226, 'yr_of_estab': 1991, 'region_of_employment': 'Midwest', 'prevailing_wage': 156251.17, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
48: {'_id': ObjectId('65ecad12116c88192e9c27ac'), 'case_id': 'EZYV49', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2405, 'yr_of_estab': 1933, 'region_of_employment': 'South', 'prevailing_wage': 86022.02, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49: {'_id': ObjectId('65ecad12116c88192e9c27ad'), 'case_id': 'EZYV50', 'continent': 'Asia', 'education_of_employee': 'Doctorate', 'has_job_experience': 'N', 'requires_job_training': 'Y', 'no_of_employees': 2171, 'yr_of_estab': 1960, 'region_of_employment': 'Northeast', 'prevailing_wage': 49565.37, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
50: {'_id': ObjectId('65ecad12116c88192e9c27ae'), 'case_id': 'EZYV51', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 746, 'yr_of_estab': 1991, 'region_of_employment': 'Midwest', 'prevailing_wage': 66191.41, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
51: {'_id': ObjectId('65ecad12116c88192e9c27af'), 'case_id': 'EZYV52', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 3129, 'yr_of_estab': 2003, 'region_of_employment': 'Midwest', 'prevailing_wage': 95623.2, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
52: {'_id': ObjectId('65ecad12116c88192e9c27b0'), 'case_id': 'EZYV53', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1647, 'yr_of_estab': 1998, 'region_of_employment': 'Midwest', 'prevailing_wage': 115014.05, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [13]:
import pandas as pd
df = pd.DataFrame(list(collection.find()))

In [14]:
df.head()

,_id,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,65ecad12116c88192e9c277c,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,65ecad12116c88192e9c277d,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,65ecad12116c88192e9c277e,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,65ecad12116c88192e9c277f,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,65ecad12116c88192e9c2780,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

```python
## If you are getting timeout issue

import certifi
client = pymongo.MongoClient(CONNECTION_URL, tlsCAFile=certifi.where())
# TO CREATE THE DATABASE
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]
# TO INSERT DATA INTO THE COLLECTION
rec = collection.insert_many(data)

```

In [10]:
if "_id" in df.columns.to_list():
    df = df.drop(columns=["_id"], axis=1)

In [11]:
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified